import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// Create dist directory if it doesn't exist
if (!fs.existsSync("dist")) {
    fs.mkdirSync("dist");
}

// Copy manifest.json to dist
fs.copyFileSync("manifest.json", "dist/manifest.json");

// Copy styles.css to dist
fs.copyFileSync("src/styles.css", "dist/styles.css");

const buildOptions = {
    banner: {
        js: banner,
    },
    entryPoints: ["src/main.ts"],
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...builtins,
    ],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "dist/main.js",
    plugins: [{
        name: 'watch-plugin',
        setup(build) {
            build.onEnd(result => {
                if (result.errors.length > 0) {
                    console.error('Build failed:', result.errors);
                } else {
                    console.log('Build succeeded');
                }
            });
        },
    }],
};

if (prod) {
    console.log('Building production bundle...');
    await esbuild.build(buildOptions);
} else {
    console.log('Starting development build...');
    const ctx = await esbuild.context(buildOptions);
    await ctx.watch();
} 