name: Create Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Extract version from package.json
      id: get_version
      run: |
        version=$(jq -r '.version' package.json)
        echo "Version found: $version"
        echo "version=$version" >> $GITHUB_OUTPUT

    - name: Create ZIP file
      run: |
        mkdir -p release
        cp manifest.json release/
        cp dist/main.js release/
        cp dist/styles.css release/
        cd release && zip -r ../obsidian-notes-sync-${{ steps.get_version.outputs.version }}.zip .
        cd .. && ls -la

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.get_version.outputs.version }}
        name: Release ${{ steps.get_version.outputs.version }}
        draft: false
        prerelease: false
        files: |
          obsidian-notes-sync-${{ steps.get_version.outputs.version }}.zip
          manifest.json
          dist/main.js
          dist/styles.css
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


